### PR TITLE
Better support for retries

### PR DESCRIPTION
**Pull request by mukundgoel**
Potential fix for #23 

Opened to get a code review and your thoughts on this.

@geekdave @Maciek416

### CODE REVIEW

**Comment by geekdave** [comment]
@mukundgoel thanks for this!  since the original issue is about misleading terminal output, could you please paste some before/after examples demonstrating how this PR fixes the confusing/misleading logs?

**Comment by mukundgoel** [comment]
Ya i forgot to put that as part of the PR.. just give me some time will add that as well. Thanks!

**Comment by mukundgoel** [comment]
I modified the response for posting it here... The only thing this PR is changing is how `(retry 1 / 3)` is printed.

```
Running 4 tests with 32 workers with safari @1024x768, chrome @1280x1024, ie @1280x1024, firefox @1280x1024

--> Worker 4, tunnel id: sauce_tunnel_name, mock port:12009, running test: test-file.js @firefox res:1280x1024
--> Worker 3, tunnel id: sauce_tunnel_name, mock port:12006, running test: test-file.js @ie res:1280x1024
--> Worker 2, tunnel id: sauce_tunnel_name, mock port:12003, running test: test-file.js @chrome res:1280x1024
--> Worker 1, tunnel id: sauce_tunnel_name, mock port:12000, running test: test-file.js @safari res:1024x768
(1 / 4) <-- Worker 2 PASS  test-file.js @chrome res:1280x1024 
(2 / 4) <-- Worker 4 PASS  test-file.js @firefox res:1280x1024 
(retry 1 / 3) <-- Worker 3 FAIL (will retry) test-file.js @ie res:1280x1024 
--> Worker 2, tunnel id: sauce_tunnel_name, mock port:12012, running test: test-file.js @ie res:1280x1024
(retry 1 / 3) <-- Worker 1 FAIL (will retry) test-file.js @safari res:1024x768 
--> Worker 1, tunnel id: sauce_tunnel_name, mock port:12015, running test: test-file.js @safari res:1024x768
(retry 2 / 3) <-- Worker 2 FAIL (will retry) test-file.js @ie res:1280x1024 
--> Worker 2, tunnel id: sauce_tunnel_name, mock port:12018, running test: test-file.js @ie res:1280x1024
(retry 2 / 3) <-- Worker 1 FAIL (will retry) test-file.js @safari res:1024x768 
--> Worker 1, tunnel id: sauce_tunnel_name, mock port:12021, running test: test-file.js @safari res:1024x768
(3 / 4) <-- Worker 2 FAIL  test-file.js @ie res:1280x1024 
(4 / 4) <-- Worker 1 FAIL  test-file.js @safari res:1024x768 
Checking for zombie processes...
Magellan giving up waiting for zombie child processes to die. Cleaning up..
Killing pid and its child pids: 85894
Done killing zombies.
```

**Comment by mukundgoel** [comment]
hi @Maciek416 @geekdave is there any other improvements needed to the output text?

**Pull request closed without merging**
