### PR TITLE
Add support for getting tests recursively starting at a root folder.

### PR DESCRIPTION
**Pull request by kriuz**
Users would be able to add mocha_tests folder "foo/bar/*" and be able to get all the mocha tests under "bar"

### CODE REVIEW

**Comment by mattfysh** [comment]
@kriuz #16 should support this by setting --recursive in `mocha_opts`

**Comment by kriuz** [comment]
@mattfysh I do have that, and it used to work before adding magellan to the workflow. My setup is magellan, rowdy (with webdriver) and mocha. I could be missing something, but seems to be setup correctly. 
My mocha.opts file looks like this:
```
--require test/setup.js
--recursive
--timeout 180000
```

**Comment by mattfysh** [comment]
@kriuz your options look good, it may just be a matter of waiting for #16 to be merged to master (uses mocha to collect the tests instead of manually parsing files/AST). we needed this for our application as our tests are written in coffeescript :)

**Comment by Maciek416** [comment]
This functionality has moved to the mocha plugin and I believe it is fully supported by Matt's additions.

**Pull request closed without merging**
