### PR TITLE
Pass selenium-server, chromedriver and phantomjs information into plugin

### PR DESCRIPTION
**Pull request by archlichking**

### CODE REVIEW

**Comment by Maciek416** [comment]
Some thoughts:

My first instinct is that we should do this in the magellan-nightwatch plugin instead, since these aspects don't apply to magellan itself but the way nightwatch test suites work, and in particular the way nightwatch includes modules by path.

One problem with my suggestion is that the nightwatch plugin doesn't have access to the modules loaded at the magellan level, so we would have to pass special information about loaded modules during initialization.

Hmmmmm

**Comment by archlichking** [comment]
Exactly, at plugin level we don't have such information, it has to be passed in from magellan. 

But since these information is bound to specific plugin, maybe we can do 
```
new TestRunClass(options, pluginOption /*where all extra options live*/);
```
and expose a `function fetchPluginOptions(args)` in each plugin repo to get such?


Or we don't need this PR at all, let user to maintain all the necessary repos in their nightwatch.json.

**Comment by Maciek416** [comment]
Some ideas:

  - Instead of passing this information in `test_runner` , I suggest we hand this to the plugin as part of magellan's `settings` object.
  - Instead of passing `isFixing*******`, we should indicate whether it is `present` by naming it `******isPresent. It's possible other plugins may be interested in this info for reasons other than fixing the integration point.

**Comment by archlichking** [comment]
BTW this PR requires
https://github.com/TestArmada/magellan-nightwatch/pull/38 
and 
https://github.com/TestArmada/magellan-nightwatch-plugin/pull/6

**Comment by Maciek416** [comment]
LGTM and ready to merge

**Pull request merged**
