### PR TITLE
Supports nightwatch.conf.js, resolves #34

### LINKED ISSUE #34: nightwatch interop does not support `nightwatch.conf.js`
Nightwatch supports providing a JS file instead of a JSON file for configuration.  I find this sort of convenient because it lets you specify remove config boilerplate with `Object.assign` and such.

This is done by using `require` in loading the config rather than `fs.readFileSync` JavaScript https://github.com/nightwatchjs/nightwatch/blob/df3794a10927286f20493e3999ce5de297f158b7/lib/runner/cli/clirunner.js#L62

### PR DESCRIPTION
**Pull request by tildedave**
Fixes #34

### CODE REVIEW

**Comment by Maciek416** [comment]
Nice!

This PR suddenly makes me very aware that our unit tests don't really test interop/framework compatibility at all. :blush: 

Since magellan makes a clone of nightwatch config for each individual run, I'm wondering if we're potentially regressing something here. Your comment on #34 says that Nightwatch allows for a JS configuration in addition to a JSON. I'm curious what the written-out cloned config looks like, i.e. https://github.com/TestArmada/magellan/blob/master/src/interop/magellan-nightwatch/rewrite_config.js#L78 and whether all bases are covered (sauce settings, selenium port, sauce connect tunnel id).

**Comment by Maciek416** [comment]
I'm giving this a whirl with some of our internal suites.

**Comment by tildedave** [comment]
Checking this out on my end too.  We have a pretty elaborate setup involving running multiple selenium servers locally with a `SELENIUM_PORT` environment variable.  This gets specified in both the "base options" (start server) and the "environment options" (connect to server).

I'll let you know what I find.  Definitely didn't feel good about submitting this without test coverage but wasn't sure how best to handle that :wink:

**Comment by tildedave** [comment]
I think specifically that 

```javascript
  if (options.localSeleniumPort) {
    // Local-testing selenium port (non-sauce)
    // Tell nightwatch to both start and connect to a selenium server on port {seleniumPort}
    conf.selenium.port = options.localSeleniumPort;
    conf.test_settings.default.selenium_port = options.localSeleniumPort;
  }
```

is not compatible with non-"default" environments, e.g. if an environment overrides `selenium_port`, this would ideally be rewritten by magellan.

**Comment by tildedave** [comment]
(We're not yet on saucelabs - this is coming "soon" (tm) so for now this is my use case.)

**Comment by Maciek416** [comment]
**re: Local overriding:** I have a feeling this is totally okay. Magellan still goes through the motions of portioning out ports for you and writing config, then your own code can happily choose to ignore that and do whatever it wants.

**re: Test coverage:** This is kinda rough right now due to being early days, but I'll try to whip something up. Right now our boilerplates effectively serve as a smoke test for integrations, but we gotta get more mechanical about this.

**Comment by Maciek416** [comment]
So far so good on `phantomjs`. Sauce is next.

**Comment by Maciek416** [comment]
@tildedave Do you mind showing me what one of these JS-based config files looks like?

**Comment by Maciek416** [comment]
(so far so good with sauce with classic JSON-style config).

**Comment by tildedave** [comment]
This is what I'm using now.  `USE_MAGELLAN` is included because I think there's an issue with `options.localSeleniumPort` where it needs to also override environments other than `default`.  The main reason for this complexity is to allow `SELENIUM_PORT` to be specified in Jenkins so that each job starts a different selenium server.  Yes this is a bit of a hack!

```
Object.assign = require('object-assign');

var SELENIUM_PORT = process.env.SELENIUM_PORT || 4444;

var portOption = {};
if (!process.env.USE_MAGELLAN) {
    portOption.selenium_port = SELENIUM_PORT;
}

var commonOptions = Object.assign({
    "exclude": ["./assertions", "./pages", "./commands"],
    "launch_url" : "http://localhost",
    "silent": true,
    "screenshots" : {
        "enabled" : true,
        "on_failure" : true,
        "on_error" : true,
        "path" : "test/screenshots"
    }
}, portOption);

module.exports = {
    "src_folders": ["test"],
    "output_folder": "test/output",
    "custom_commands_path": "commands",
    "custom_assertions_path": "assertions",
    "page_objects_path": "pages",
    "globals_path": "globals.js",
    "selenium" : {
        "start_process" : true,
        "server_path" : "node_modules/selenium-server/lib/runner/selenium-server-standalone-2.45.0.jar",
        "log_path" : "",
        "host" : "127.0.0.1",
        "port" : SELENIUM_PORT,
        "cli_args" : {
            "webdriver.chrome.driver" : "node_modules/chromedriver/lib/chromedriver/chromedriver",
            "webdriver.ie.driver" : ""
        }
    },
    "skip_testcases_on_fail": false,
    "test_settings" : {
        "default" : Object.assign({
            "desiredCapabilities": {
                "browserName": "chrome",
                "javascriptEnabled": true,
                "acceptSslCerts": true,
                "chromeOptions": {
                    "args": [
                        "--no-sandbox",
                        "--window-size=1200,1024"
                    ]
                }
            }
        }, commonOptions),
        "chrome" : Object.assign({
            "desiredCapabilities": {
                "browserName": "chrome",
                "javascriptEnabled": true,
                "acceptSslCerts": true,
                "chromeOptions": {
                    "args": [
                        "--no-sandbox",
                        "--window-size=1200,1024"
                    ]
                }
            }
        }, commonOptions),
        "desktop" : Object.assign({
            "desiredCapabilities": {
                "browserName": "chrome",
                "javascriptEnabled": true,
                "acceptSslCerts": true,
                "chromeOptions": {
                    "args": [
                        "--no-sandbox",
                        "--window-size=1200,1024"
                    ]
                }
            }
        }, commonOptions),
        "firefox" : Object.assign({
            "desiredCapabilities": {
                "browserName": "firefox",
                "trustAllSSLCertificates": true
            }
        }, commonOptions),
        "phantomjs": Object.assign({
            "desiredCapabilities": {
                "browserName": "phantomjs",
                "javascriptEnabled": true,
                "acceptSslCerts": true,
                "phantomjs.cli.args" : ["--ignore-ssl-errors=true"]
            }
        }, commonOptions),
        "mobile": Object.assign({
            "desiredCapabilities": {
                "browserName": "chrome",
                "javascriptEnabled": true,
                "acceptSslCerts": true,
                "chromeOptions": {
                    "args": [
                        "--user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A4449d Safari/9537.53",
                        "--window-size=320,568"
                    ]
                }
            }
        }, commonOptions)
    }
};
```

**Comment by Maciek416** [comment]
Thanks for this. I'm gonna try morphing ours into the above form and see if I can break it.

**Comment by Maciek416** [comment]
Ok. This doesn't seem to cause any problems at all. I think we are a go!

**Comment by Maciek416** [comment]
Published in `testarmada-magellan@1.6.7`

**Comment by tildedave** [comment]
Thanks so much!

**Pull request merged**
