### PR TITLE
first attempt on integrating protractor

### PR DESCRIPTION
**Pull request by abhagupta**
This is still a work in progress. Wanted to send it your way before I leave for vacation.  

Todo : 
1. use acorn to parse the test/spec files
2. remove duplicate code from get_tests.js. May be find a cleaner and concise way to read spec files
3. the protractor library needs the conf.js file in exports.config. Right now I have mimicked the nightwatch way by creating a JSON, but this will not work in protractor.

### CODE REVIEW

**Comment by Maciek416** [comment]
Nice. I believe my existing work with `acorn` scanning of mocha tests will take care of the first TODO.

**Comment by geekdave** [comment]
@abhagupta do you want to leave this PR open?  if the work is stalled for now, but may be picked back up at a later date, we can close the PR and leave the branch in-place.

**Comment by geekdave** [comment]
Closing until we decide to revisit this.

**Comment by mattfysh** [comment]
@geekdave qq on integrations, does it make sense to keep them in the same repo, or provided as plugins e.g. `magellan-protractor`

**Comment by Maciek416** [comment]
@mattfysh yep. We definitely have been chatting about going with plugin architecture instead of `interop`. It would help segment the project into something easier to write unit tests for and lower the mental load required to understand how the source code is structured.

**Comment by mattfysh** [comment]
that sounds awesome! ps. im putting together the tests for #16 right now, will get something up soon

**Comment by Maciek416** [comment]
@mattfysh thanks!

**Pull request closed without merging**
