### PR TITLE
Setup, teardown + listener test suite

### PR DESCRIPTION
**Pull request by Maciek416**
This PR re-brands internal reporter architecture as "listeners" to allow for a setup and teardown use case.

Notes:
  - First-ever tests for the listener (aka reporter) life cycle
  - Documented how to implement setup and teardown with listeners in the README
  - makes `listenTo()` an **optional** implementation on listener objects (as with `flush()`, previously)

Solves https://github.com/TestArmada/magellan/issues/72

/cc @geekdave

### CODE REVIEW

**Comment by mattfysh** [comment]
are you guys thinking of adopting test practices for the framework itself? it seems most PRs are added with no test coverage... and irony aside, I'm now hesitant to bring this tool into our testing stack (although we are currently blocked on #18 which adds support for root-level hooks and mocha.opts processing before test suite collection for e.g. enabling coffeescript test files)

**Comment by Maciek416** [comment]
@mattfysh You're absolutely right. The irony is off the charts. Your comment is making me think maybe we should step back and spend some quality time getting our house in order in this respect before charging forward. I appreciate the kick in the pants :jeans:

**Comment by Maciek416** [comment]
Reworking this PR a bit. It's needlessly adding redundant functionality.

Instead of adding new functionality, I'm doing the following:

  - Internally renaming `reporters` to `listeners`. Same existing API.
  - Adding unit tests for listeners to check the listener lifecycle: `new`, `initialize`, `listenTo`, message delivery, and `flush`.
  - setup/teardown will be implemented as a listener instead of as a new feature.

**Comment by Maciek416** [comment]
Removed new functionality (it was redundant). Added several tests, cleaned up README to document how to implement setup / teardown as a listener.

**Comment by Maciek416** [comment]
TODO: I'd like to add a test for `setup_teardown` itself, which will require running the magellan binary.

**Comment by Maciek416** [comment]
https://github.com/TestArmada/magellan/issues/79

**Pull request merged**
